### ISSUE TITLE
replace `List` with a `class` wrapped `List`

### ISSUE THREAD

**Issue by mhmerrill** [mhmerrill/LisExpr#2]
- wrap `List` in a class to make it `shared` this is to prevent copying
- use `forward` to get at the `List` interface

the original code has nasty copying going on during the parse which makes it N**2 copying.
what we really want is to build the list up as we go and not copy it every time we add and element.

**Comment by mhmerrill** [comment]
@bmcdonald3 you showed me a piece of code related to this, could you drop a comment here so I can work on it...

```chapel
class ListClass
{
    use List;
    type etype;
    forwarding var l: list(etype);

    proc init(type etype) {
        this.etype = etype;
        this.l = new list(etype) // is this necessary? does init() get forwarded?
    }
}

var l = new shared ListClass(int);

```

**Comment by bmcdonald3** [comment]
Yes, here is what I was thinking:

```
use List; // I don't think you can put this in the class definition
class ListClass
{
    type etype;
    forwarding var l: list(etype);

     // new init not required, values forwarded
}

var l = new shared ListClass(int);
// use `l` as regular list, all methods from the record are accessible on the class
l.append(5);
```

**Comment by bmcdonald3** [comment]
I was also planning on taking a look at transitioning to the forwarded class in the lisp code this week, but don't want to step on your toes if you would like to work on that.

**Comment by mhmerrill** [comment]
> I was also planning on taking a look at transitioning to the forwarded class in the lisp code this week, but don't want to step on your toes if you would like to work on that.

I am ok with you doing this, just leave me some comments so I can follow along ;-)
